---
title: "Functions"
author: "Leslie M. Hartten"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(roxygen2)
#source("conversions.R") #set of functions that are local to a project; not rendered in Markdown
```

# Create some data for examples
```{r}

airtempF <- c(212, 30.3, 75, 32, -40)

celsius1 <- (airtempF[1]-32)*5/9
celsius2 <- (airtempF[2]-32)*5/9
celsius3 <- (airtempF[3]-32)*5/9
celsius4 <- (airtempF[4]-32)*5/9
celsius5 <- (airtempF[5]-32)*5/9
```

# Write a function for F to C conversion

```{r}
#' Convert from Fahrenheit to Celsius
#'
#' A much more detailed explanation of how the function works.
#' @param fahr represents a numeric input in degrees Fahrenheit
#' @return the temperature in Celsius
#' @export 
#' @example fahr_to_celsius(212)
#function_name <- function(input)
fahr_to_celsius <- function(fahr) {
  # check if fahr is numeric  (see 'error', 'warning', 'message')
  stopifnot(is.numeric(fahr))
  
  celsius <- (fahr-32)*5/9
  return(celsius)
}

airtempC1 <- (airtempF[1]-32)*5/9
airtempC1
airtempC1 == celsius1

airtempF
airtempC <- fahr_to_celsius(airtempF)
airtempC

#celsiusABC <- fahr_to_celsius('abc') #yields Error in fahr_to_celsius(airtemps) : !is.numeric(fahr) is not TRUE
```

# Write a function fo convert C to F

```{r}
#' Convert from Celsius to Fahrenheit
#'
#' A much more detailed explanation of how the function works.
#' @param celsius represents a numeric input in degrees Celsius
#' @return the temperature in Fahrenheit
#' @export 
#' @example celsius_to_fahr(212)
#function_name <- function(input)
celsius_to_fahr <- function(celsius) {
  # check if celsius is numeric  (see 'error', 'warning', 'message')
  stopifnot(is.numeric(celsius))
  
  fahr <- (celsius)*9/5 + 32
  return(fahr)
}

airtempFnew <- celsius_to_fahr(airtempC)
```

